### ISSUE TITLE
"usage" not a valid command

### ISSUE THREAD

**Issue by naadhira** [hazelcast/hazelcast-member-tool#11]
Screen cap follows. If it isn't a valid command, remove it from the -help output.

*****

Usage:  hazelcast-member COMMAND

Basic Commands:
  logs        display logs for a member
  start       start a Hazelcast member
  status      display process status for started members
  stop        stop a member

Other Commands:
  list        print started members IDs
  **usage       display usage information**

Options:
  -h or --help
        display usage and options

  -v or --version
        print Hazelcast version

Run 'hazelcast-member help COMMAND' for more information on a command.

**hazelcast-member: 'usage' is not a valid command.**
HendysMacBook:~ hendyappleton$

**Comment by googlielmo** [comment]
good spot @naadhira, thanks! fixed on next release
