### ISSUE TITLE
Permission issue starting hazelcast-member

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast-member-tool#5]
`sudo apt-get install hazelcast-member`
then try to run `hazelcast-member start`
gives...
`mkdir: cannot create directory ‘/var/run/hazelcast’: Permission denied
mkdir: cannot create directory ‘/var/run/hazelcast/angry_northcutt’: No such file or directory
Error: Can't create temp directory`

User shouldn't have to `sudo` all the time to run hazelcast.

**Comment by dbrimley** [comment]
just pinging this.

**Comment by googlielmo** [comment]
I cannot reproduce this issue on Ubuntu 18.04 LTS. Which version are you using?

**Comment by dbrimley** [comment]
I did a `sudo apt-get purge` and then reinstalled.

It works now???

I'll close and re-open if I get the issue again.
